elab/urls.py
# (elabs urls)

from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from elab.views import *

urlpatterns = [
    url(r'^$', Login.as_view(), name='login'),
    url(r'^actions/$', login_required(actions), name='actions'),
    url(r'^logout/$', login_required(signout), name='signout'),
    url(r'^getallergy/$', get_allergy),
    url(r'^addpatient/$', login_required(PatientCreate.as_view()), name='create-patient'),
    url(r'^patients/$', PatientList.as_view(), name='patient-list'),
    url(r'^patientvisit/$', login_required(PatientVisits.as_view()), name='patient-visit'),
    url(r'^patientsserved/$', PatientVisitList.as_view(), name='patients-served'),
    url(r'^testrequest/$', login_required(RequestTest.as_view()), name='test-request'),
    url(r'^requestedtests/$', TestsRequestedList.as_view(), name='tests-requested'),
    url(r'^edittest/(?P<id>\d+)/$', login_required(EditTest.as_view()), name='test-edit'),
    url(r'^deletetest/(?P<id>\d+)/$', login_required(DeleteTest.as_view()), name='delete-test'),
    url(r'^notifications/$', notifications, name='notifications')
]

elabs/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('elab.urls')),
]

elab/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Patient(models.Model):
    # (This is the patients' model class with basic information about them)

    INSURANCE_CHOICES = (
        ('TYPE 1', 'TYPE 1'),
        ('TYPE 2', 'TYPE 2'),
        ('TYPE 3', 'TYPE 3'),
        ('TYPE 4', 'TYPE 4'),
    )
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=15, null=False)
    last_name = models.CharField(max_length=15, null=False)
    middle_name = models.CharField(max_length=15, blank=True)
    date_of_birth = models.DateField()
    email = models.EmailField(max_length=254)
    mobile_number = models.CharField(max_length=10, blank=False, null=False)
    id_number = models.CharField(max_length=10)
    passport_number = models.CharField(max_length=10)
    allergy = models.TextField()
    insurance = models.CharField(max_length=10, choices=INSURANCE_CHOICES, blank=True)

    def __str__(self):
        return '{0}'.format(self.first_name)


class PatientVisit(models.Model):
    # (This is the basic information about a patient's visit)

    VISIT_CHOICES = (
        ('in patient', 'in patient'),
        ('out patient', 'out patient'),
    )
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    visit = models.CharField(max_length=15, blank=False, null=False, choices=VISIT_CHOICES)
    diagnosis = models.TextField()
    current_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return '{0} {1}'.format(self.patient.first_name, self.patient.last_name)


class Laboratory(models.Model):
    # (adds laboratories in the system)
    name = models.CharField(max_length=25, blank=False, null=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Laboratories'


class Test(models.Model):
    # (Tests models)
    SPECIMEN_CHOICES = (
        ('SPECIMEN 1', 'SPECIMEN 1'),
        ('SPECIMEN 2', 'SPECIMEN 2'),
        ('SPECIMEN 3', 'SPECIMEN 3'),
    )
    patient_visit = models.ForeignKey(PatientVisit, on_delete=models.CASCADE)
    laboratory = models.ForeignKey(Laboratory, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)
    specimen = models.CharField(max_length=10, choices=SPECIMEN_CHOICES)
    result_expected = models.CharField(max_length=20, null=False, blank=False)
    date_rquested = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

elab/forms.py
from django import forms
from .models import *


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['first_name', 'last_name', 'middle_name', 'date_of_birth',
                  'email', 'mobile_number', 'id_number', 'passport_number',
                  'allergy', 'insurance']

    def save(self, user):
        patient = super(PatientForm, self).save(commit=False)
        patient.added_by = user
        patient.save()
        return True


class PatientVisitForm(forms.ModelForm):
    class Meta:
        model = PatientVisit
        fields = ['visit', 'diagnosis']

    def save(self, user, sickpatient):
        visit = super(PatientVisitForm, self).save(commit=False)
        visit.patient = sickpatient
        visit.doctor = user
        visit.save()
        return True


class TestForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['patient_visit', 'specimen', 'result_expected']

    def save(self, laboratory, tests):
        test = super(TestForm, self).save(commit=False)
        test.laboratory = laboratory
        test.name = tests
        test.save()
        return True

class TestUpdateForm(forms.ModelForm):
    class Meta:
        model = Test
        fields = ['specimen', 'result_expected']
        

elab/views.py
# (import instaces that provide specific functionality)
from django.shortcuts import render  # (rendering a template)
from django.contrib.auth import authenticate, login, logout  # (handles authentication)
from django.http import HttpResponseRedirect, JsonResponse  # (response returning)
from django.views.generic import View, ListView  # (class based views)
from django.core.urlresolvers import reverse  # ( redirects to a url defined by name in the urls.py file)
from .models import *  # (imports all models defined in the models.py)
from .forms import *  # (import all forms)
import time
# Create your views here.


def actions(request):
    # renders the actions template
    return render(request, 'actions.html', {'doctor': request.user.username})


def signout(request):
    # handles the log out functionality
    logout(request)
    return HttpResponseRedirect('/')


def notifications(request):
    return render(request, 'notifications.html', {'doctor': request.user.username})


def get_allergy(request):
    # returns a json response of the chosen patient's allergy
    time.sleep(2)
    patient_id = request.GET['patient']
    patient = Patient.objects.get(id=patient_id)
    allergy = patient.allergy
    return JsonResponse(allergy, safe=False)


class Login(View):
    # this view handles authentication
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')

    def post(self, request, *args, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('actions'))
        else:
            return render(request, 'login.html', {'authentication': 'failed'})


class PatientCreate(View):
    # adding a patient. Can be done by any doctor
    def get(self, request, *args, **kwargs):
        context = {'form': PatientForm()}
        return render(request, 'patient_create_form.html', context)

    def post(self, request, *args, **kwargs):
        form = PatientForm(request.POST)
        if form.is_valid():
            form.save(request.user)
            return HttpResponseRedirect(reverse('actions'))
        else:
            context = {'form': form}
            return render(request, 'patient_create_form.html', context)


class PatientList(ListView):
    # returns the patients the logged in doctor has added
    template_name = 'patient_list.html'
    context_object_name = 'patients'

    def get_queryset(self):
        time.sleep(2)
        return Patient.objects.filter(added_by=self.request.user)


class PatientVisits(View):
    # Records a patient visit's details including diagnosis
    def get(self, request, *args, **kwargs):
        context = {'form': PatientVisitForm()}
        patients = Patient.objects.filter(added_by=request.user).only('id', 'first_name', 'last_name')
        context['patients'] = patients
        return render(request, 'patient_visit.html', context)

    def post(self, request, *args, **kwargs):
        form = PatientVisitForm(request.POST)
        if form.is_valid():
            patient = Patient.objects.get(id=request.POST['patient'])
            form.save(request.user, patient)
            return HttpResponseRedirect(reverse('actions'))
        else:
            context = {'form': form}
            patients = Patient.objects.filter(added_by=request.user).only('id', 'first_name', 'last_name')
            context['patients'] = patients
            return render(request, 'patient_visit.html', context)


class PatientVisitList(ListView):
    # shows the patients the logged in doctor has served
    template_name = 'patient_visit_list.html'
    context_object_name = 'visits'

    def get_queryset(self):
        time.sleep(2)
        return PatientVisit.objects.select_related('doctor', 'patient').filter(doctor=self.request.user)


class RequestTest(View):
    # this is where a doctor requests one or more tests
    def get(self, request, *args, **kwargs):
        context = {'form': TestForm()}
        laboratories = Laboratory.objects.all()
        context['laboratories'] = laboratories
        return render(request, 'test_request.html', context)

    def post(self, request, *args, **kwargs):
        form = TestForm(request.POST)
        if form.is_valid():
            laboratory = Laboratory.objects.get(id=request.POST['laboratory'])
            tests = []
            if 'test1' in request.POST:
                tests.append(request.POST['test1'])
            if 'test2' in request.POST:
                tests.append(request.POST['test2'])
            if 'test3' in request.POST:
                tests.append(request.POST['test3'])

            tests = ', '.join(tests)
            form.save(laboratory, tests)
            return HttpResponseRedirect(reverse('actions'))
        else:
            context = {'form': form}
            laboratories = Laboratory.objects.all()
            context['laboratories'] = laboratories
            return render(request, 'test_request.html', context)


class TestsRequestedList(ListView):
    # Displays the tests requested by a doctor
    template_name = 'tests_requested.html'
    context_object_name = 'tests'

    def get_queryset(self):
        time.sleep(2)
        return Test.objects.select_related('laboratory', 'patient_visit').filter(patient_visit__doctor=self.request.user)


class EditTest(View):
    def get(self, request, id, *args, **kwargs):
        test = Test.objects.get(id=id)
        form = TestUpdateForm(instance=test)
        laboratories = Laboratory.objects.all()
        context = {}
        context['form'] = form
        context['laboratories'] = laboratories
        context['id'] = id
        return render(request, 'edit_test.html', context)

    def post(self, request, *args, **kwargs):
        form = TestUpdateForm(request.POST)
        id = request.POST['test_id']
        test = Test.objects.get(id=id)
        if form.is_valid():
            laboratory = Laboratory.objects.get(id=request.POST['laboratory'])
            tests = []
            if 'test1' in request.POST:
                tests.append(request.POST['test1'])
            if 'test2' in request.POST:
                tests.append(request.POST['test2'])
            if 'test3' in request.POST:
                tests.append(request.POST['test3'])

            specimen = request.POST['specimen']
            result_expected = request.POST['result_expected']
            tests = ', '.join(tests)

            test.laboratory = laboratory
            test.name = tests
            test.specimen = specimen
            test.result_expected = result_expected
            test.save()
            return HttpResponseRedirect(reverse('actions'))
        else:
            context = {'form': form}
            laboratories = Laboratory.objects.all()
            context['laboratories'] = laboratories
            context['id'] = id
            return render(request, 'edit_test.html', context)


class DeleteTest(View):
    def get(self, request, id, *args, **kwargs):
        return render(request, 'test_delete.html', {'id': id})

    def post(self, request, *args, **kwargs):
        id = request.POST['test_id']
        test = Test.objects.get(id=id)
        test.delete()
        return HttpResponseRedirect(reverse('actions'))

elab/templates/actions.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
		<div class="well well-lg">
			<p>
				<span class="glyphicon glyphicon-user"></span>
				welcome {{ doctor }}
			</p>
		</div>
		<div class="btn-group btn-group-justified" role="group">
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Patients
				<span class="caret"></span> 
				</button>
				<ul class="dropdown-menu">
					<li><a href="{% url 'create-patient' %}">Add patient</a></li>
     				<li><a href="{% url 'patient-list' %}" data-elabs="get-patients">View patients</a></li>
				</ul>
			</div>
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Visit
				<span class="caret"></span> 
				</button>
				<ul class="dropdown-menu">
					<li><a href="{% url 'patient-visit' %}">New visit</a></li>
     				<li><a href="{% url 'patients-served' %}" data-elabs="get-served-patients">View visits served </a></li>
				</ul>
			</div>
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> Tests
				<span class="caret"></span> 
				</button>
				<ul class="dropdown-menu">
					<li><a href="{% url 'test-request' %}">Request test</a></li>
     				<li><a href="{% url 'tests-requested' %}" data-elabs="get-requested-tests">View tests requested</a></li>
				</ul>
			</div>
			<div class="btn-group" role="group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="	false"> Account
				<span class="caret"></span> 
				</button>
				<ul class="dropdown-menu">
					<li><a href="{% url 'notifications' %}">Notifications</a></li>
     				<li><a href="{% url 'signout' %}">Log out</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container-fluid" id="content-section">
		
	</div>
{% endblock %}

elab/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes"/>


	<title>Elabs | </title>

	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'css/dpLoading-2.x-min.css' %}" rel="stylesheet">
	<link href="{% static 'css/dpLoading-2.x-skin-grey-min.css' %}" rel="stylesheet">
</head>
<body>
	<div class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<a class="navbar-brand" href="/">
					Elabs 
				</a>
			</div>
		</div>
	</div>
	<section>
		{% block content %}

		{% endblock %}
	</section>
<script type="text/javascript" src="{% static 'scripts/jquery-2.2.3.min.js'%}"></script>
<script type="text/javascript" src="{% static 'scripts/bootstrap.js'%}"></script>
<script type="text/javascript" src="{% static 'scripts/dpLoading-2.x-min.js'%}"></script>
<script type="text/javascript" src="{% static 'scripts/elabs.js'%}"></script>
</body>
</html>

elab/templates/edit_test.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6 col-xs-12 col-md-offset-2">
        <form action="" method="post">{% csrf_token %}
            <input type='hidden' name="test_id" value="{{ id }}" />
            <div id="div_id_laboratory" class="form-group">
                <label for="id-laboratory" class="control-label"> Laboratory </label>
                <div class="controls">
                    <select class="select form-control" id="id_laboratory" name="laboratory">
                        <option value="" selected></option>
                        {% for laboratory in laboratories %}
                            <option value="{{ laboratory.id }}"> {{ laboratory.name }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div id="div_id_test" class="form-group">
               <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 1" name="test1">
                        Test 1
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 2" name="test2">
                        Test 2
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 3" name="test3">
                        Test 3
                    </label>
                </div>
            </div>
            {{ form|crispy }}
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
                <div class="col-md-6 col-xs-12">
                    <a href="{% url 'delete-test'  id  %}" class="btn btn-default">Delete test</a>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

elab/templates/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block content %}
	{% include 'welcomejumbotron.html' %}
	<div class="col-md-6 col-xs-12 col-md-offset-2">
		<form action="{% url 'login' %}" method="post">
			{% csrf_token %}
			<fieldset>
				<legend>Log in</legend>
				{% if authentication %}
					<div class="alert alert-danger" role="alert">Incorrect login credentials </div>
				{% endif %}
				<div class="form-group">
					<label for="username">Username</label>
					<input type="text" class="form-control" id="username" placeholder="username" name="username">
				</div>
				<div class="form-group">
					<label for="password">Username</label>
					<input type="password" class="form-control" id="password" placeholder="password" name="password">
				</div>
			</fieldset>
			<button type="submit" class="btn btn-default">log in</button>
		</form>
	</div>
{% endblock %}

elab/templates/notifications.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-xs-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"> Notifications </h3>
                    </div>
                    <div class="panel-body">
                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                submitted results <span class="badge"> 4 </span>
                            </a>
                            <a href="#" class="list-group-item">
                                Tests not performed <span class="badge"> 2 </span>
                            </a>
                        </div>
                    </div>
                    <div class="panel-footer">
                       {{ doctor }} Elabs
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

elab/templates/patient_create_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
	<div class="col-md-6 col-xs-12 col-md-offset-2">
		<form action="" method="post">{% csrf_token %}
		    {{ form|crispy }}
		    <input type="submit" value="Create" class="btn btn-default" />
		</form>
	</div>
{% endblock %}

elab/templates/patient_list.html
{% if patients %}
	<div class="panel panel-default" style="margin-top:10px">
		<div class="panel-heading">
			<h2 class="panel-title"> Patients </h2>
		</div>
		<table class="table">
			<thead>
				<tr>
					<th>Name</th>
					<th>DOB</th>
					<th>Email</th>
					<th>Mobile number</th>
					<th>Id number</th>
					<th>Passport number</th>
					<th>Allergy</th>
					<th>Insurance</th>
				</tr>
			</thead>
			<tbody>
				{% for patient in patients %}
					<tr>
						<td>{{ patient.first_name }} {{ patient.last_name }} {{ patient.middle_name }}</td>
						<td> {{ patient.date_of_birth }} </td>
						<td>{{ patient.email }}</td>
						<td>{{ patient.mobile_number }}</td>
						<td>{{ patient.id_number }}</td>
						<td>{{ patient.passport_number }}</td>
						<td>{{ patient.allergy }}</td>
						<td>{{ patient.insurance }}</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>	
	</div>
{% else %}
	<div class="alert alert-danger" role="alert" style="margin-top:10px;">
		<span class="glyphicon glyphicon-remove"></span>
		Sorry, you have not added any patients
	</div>
{% endif %}

elab/templates/patient_visit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6 col-xs-12 col-md-offset-2">
        <div>
            <div class="alert alert-info" role="alert" data-elabs="allergy-section">
                <h3>Allergy</h3>
                <p></p>
            </div>
        </div>
        <form action="" method="post">{% csrf_token %}
            <div id="div_id_patient" class="form-group">
                <label for="id-patient" class="control-label requiredField"> Patient </label>
                <div class="controls">
                    <select class="select form-control" id="id_patient" name="patient" data-elabs="patient-select">
                        <option value="">Please choose a patient</option>
                        {% for patient in patients %}
                            <option value="{{ patient.id }}"> {{ patient.first_name }} {{ patient.last_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            {{ form|crispy }}
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
{% endblock %}

elab/templates/patient_visit_list.html
{% if visits %}
    <div class="panel panel-default" style="margin-top:10px">
        <div class="panel-heading">
            <h2 class="panel-title"> Patients served </h2>
        </div>
        <table class="table container-fluid">
            <thead>
                <tr>
                    <th>Doctor</th>
                    <th>Patient</th>
                    <th>Allergy</th>
                    <th>Diagnosis</th>
                    <th>Visit</th>
                    <th>Date</th>
                </tr>
            </thead>
            <tbody>
                {% for visit in visits %}
                    <tr>
                        <td>{{ visit.doctor.username }}</td>
                        <td>{{ visit.patient.first_name }} {{ visit.patient.last_name }}</td>
                        <td>{{ visit.patient.allergy }}</td>
                        <td>{{ visit.diagnosis }}</td>
                        <td>{{ visit.visit }}</td>
                        <td>{{ visit.current_date }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
    <div class="alert alert-danger" role="alert" style="margin-top:10px;">
        <span class="glyphicon glyphicon-remove"></span>
        Sorry, you have not served any patients yet.
    </div>
{% endif %}

elab/templates/test_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" name="test_id" value="{{ id }}">
            <p>Are you sure you want to delete this test?</p>
            <input type="submit" value="Confirm"  class="btn btn-default" />
        </form>
    </div>    
{% endblock %}

elab/templates/test_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="col-md-6 col-xs-12 col-md-offset-2">
        <form action="" method="post">{% csrf_token %}
            <div id="div_id_laboratory" class="form-group">
                <label for="id-laboratory" class="control-label"> Laboratory </label>
                <div class="controls">
                    <select class="select form-control" id="id_laboratory" name="laboratory">
                        <option value="" selected></option>
                        {% for laboratory in laboratories %}
                            <option value="{{ laboratory.id }}"> {{ laboratory.name }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div id="div_id_test" class="form-group">
               <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 1" name="test1">
                        Test 1
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 2" name="test2">
                        Test 2
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="Test 3" name="test3">
                        Test 3
                    </label>
                </div>
            </div>
            {{ form|crispy }}
            <div class="row">
                <div class="col-md-6 col-xs-12">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </form>
    </div>
{% endblock %}

elab/templates/tests_requested.html
{% if tests %}
    <div class="panel panel-default" style="margin-top:10px">
        <div class="panel-heading">
            <h3 class="panel-title"> Tests requested </h3>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Doctor</th>
                    <th>Patient</th>
                    <th>Test(s)</th>
                    <th>Laboratory</th>
                    <th>Date requested</th>
                    <th>Results expected after</th>
                </tr>
            </thead>
            <tbody>
                {% for test in tests %}
                        <tr>  
                            <td>{{ test.patient_visit.doctor }}</td>
                            <td>{{ test.patient_visit.patient.first_name }}, {{ test.patient_visit.patient.last_name }}</td>
                            <td><a href="{% url 'test-edit' test.id  %}"> {{ test.name }} </a></td>
                            <td>{{ test.laboratory.name }}</td>
                            <td>{{ test.date_rquested  }}</td>
                            <td>{{ test.result_expected }}</td>
                        </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
     <div class="alert alert-danger" role="alert" style="margin-top:10px;">
        <span class="glyphicon glyphicon-remove"></span>
        Sorry, you have not Requested any tests yet.
    </div>
{% endif %}

elab/templates/welcomejumbotron.html
<div class="container">
	<div class="jumbotron">
		<h1> WELCOME TO ELABS! </h1>
	</div>
</div>